### ISSUE TITLE
No license.

### ISSUE THREAD

**Issue by JeroenKnoops** [citizen-of-planet-earth/cf-cli-action#1]
There is no mentioning of a license in this repository.
Is this on purpose, or does it has an open source license like f.e. MIT?

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by wapacro** [comment]
Hey @JeroenKnoops,
Thanks for pointing this out. Totally forgot about it when I wrote that action. It's added now.
