### ISSUE TITLE
No functionality for cf7-cli

### ISSUE THREAD

**Issue by thatkellenguy** [citizen-of-planet-earth/cf-cli-action#3]
There are some capabilities with cf7-cli that aren't in v6 (e.g., Multiple Process Apps).  In order to make use of this, I created a pull request that simply runs the cf7-cli. 

https://github.com/citizen-of-planet-earth/cf-cli-action/pull/2

**Comment by wapacro** [comment]
Hi @thatkellenguy 
Many thanks for the contribution. I just released v2 of the action which uses CF CLI v7.
