### ISSUE TITLE
403 Forbidden when building image, on cf-cli-debian-repo.s3.amazonaws.com

### ISSUE THREAD

**Issue by tferns** [citizen-of-planet-earth/cf-cli-action#6]
```
Err:7 https://cf-cli-debian-repo.s3.amazonaws.com/ stable/main amd64 Packages
    403  Forbidden [IP: 52.218.179.1 443]
  Reading package lists...
  E: Failed to fetch https://cf-cli-debian-repo.s3.amazonaws.com/dists/stable/main/binary-amd64/Packages  403  Forbidden [IP: 52.218.179.1 443]
  E: Failed to fetch https://cf-cli-debian-repo.s3.amazonaws.com/dists/stable/main/binary-all/Packages  403  Forbidden [IP: 52.218.179.1 443]
  E: Some index files failed to download. They have been ignored, or old ones used instead.
  The command '/bin/sh -c apt-get update' returned a non-zero code: 100
  
  Warning: Docker build failed with exit code 100, back off 7.87 seconds before retry.
```

This has started occurring for me in the last ~2 hours or so, not quite sure the root cause.   I noticed there was a change on the [cloudfoundry-cli](https://github.com/cloudfoundry/cli/pull/2471) in a coincidentally similar timeframe, I've left a [comment](https://github.com/cloudfoundry/cli/pull/2471#issuecomment-1603255926) querying if it was potentially the root cause of this, however thought I'd open and issue here in-case anyone else searches online and finds nothing like me.  Please feel free to add solutions in the comments if you find a fix or the root cause, thanks.

**Comment by smitt04** [comment]
I was getting the same error switching the action from:
```yaml
uses: citizen-of-planet-earth/cf-cli-action@master
```
to:
```yaml
uses: citizen-of-planet-earth/cf-cli-action@v2
```
fixed it for me

**Comment by tferns** [comment]
@smitt04 strange, I was using v2 this entire time, running the same old workflows seem to work now!  So maybe the access issue behind the scenes was fixed? Not sure, but thanks for the suggestion! All working for me now so will close this.
